project_id = "znuwvgspjvsifnwizynd"

[functions.search-companies]
verify_jwt = false

[functions.validate-phones]
verify_jwt = false

[functions.search-by-cnae]
verify_jwt = false

[functions.lista-cnae-municipios]
verify_jwt = false

[functions.lista-cnae-cnaes]
verify_jwt = false

[functions.check-cnpjws-account]
verify_jwt = false

[functions.test-cnpjws-premium]
verify_jwt = false

[functions.search-google-maps]
verify_jwt = false

[functions.search-by-cep]
verify_jwt = false
