project_id = "znuwvgspjvsifnwizynd"

[functions.search-companies]
verify_jwt = false

[functions.validate-phones]
verify_jwt = false

[functions.search-by-cnae]
verify_jwt = false

[functions.lista-cnae-municipios]
verify_jwt = false
